os: Visual Studio 2017

skip_tags: true

environment:
  BOOST_ROOT: C:\Libraries\boost_1_67_0
  BOOST_LIBRARYDIR: C:\Libraries\boost_1_67_0\lib64-msvc-14
  APPVEYOR_REPO_TAG: true

init:
  - set PATH=c:\Python37;c:\Python37\Scripts;%PATH%
  - pip install clcache

before_build:
- clcache -s

build_script:
  - md build
  - cd build
  - cmake -G "Visual Studio 15 2017 Win64" ..
  - MSBuild Bitcoinnova.sln /p:CLToolExe=clcache.exe /p:CLToolPath=c:\Python37\Scripts\ /p:Configuration=Release /m
  - src\Release\cryptotest.exe

after_build:
  - clcache -s
  - if not defined APPVEYOR_REPO_TAG_NAME (set APPVEYOR_REPO_TAG_NAME=%APPVEYOR_REPO_COMMIT%)
  - cd src\Release
  - mkdir bitcoinnova-%APPVEYOR_REPO_TAG_NAME%
  - copy *.exe bitcoinnova-%APPVEYOR_REPO_TAG_NAME%
  - copy ..\..\..\LICENSE bitcoinnova-%APPVEYOR_REPO_TAG_NAME%
  - 7z a bitcoinnova-%APPVEYOR_REPO_TAG_NAME%-windows.zip bitcoinnova-%APPVEYOR_REPO_TAG_NAME%
  - copy bitcoinnova-%APPVEYOR_REPO_TAG_NAME%-windows.zip ..\..\..\
  
artifacts:
  - path: bitcoinnova-$(APPVEYOR_REPO_TAG_NAME)-windows.zip
    name: BitcoinNovaRelease

deploy:
  - provider: GitHub
    tag: $(APPVEYOR_REPO_TAG_NAME)
    release: $(APPVEYOR_REPO_TAG_NAME)
    auth_token:
      secure: Et6vQSczqAYwxWaphlKbymjIB3d16tJIwEHXAjxcxDMBxF+HM4bNQEuBIlEzYfU8
    repository: BitcoinNova/bitcoinnova_0.12.0.1280
    artifact: BitcoinNovaRelease
    draft: false
    force_update: true
    on:
      branch: master
      appveyor_repo_tag: true

  - provider: S3
    access_key_id:
      secure: nVmSNpabdw1WcGdTTzxAEjza8j9icu89oyXbC8fZVuM=
    secret_access_key:
      secure: TpCxPp5npMRclcwHB3dhkd9ZsEgKstS6HOnQ1VR6YObEsaPyl5dr16ZdbsOgjykj
    bucket: bitcoinnova
    region: us-east-2
    set_public: true
    folder: bitcoinnova
    artifact: releases
    on:
      appveyor_repo_name: bitcoinNova/bitcoinnova_0.12.0.1280
