version: '3'

services:
  node1:
    image: funkypenguin/bitcoinnova
    container_name: bitcoinnovatest-node1
    volumes:
      - ../bitcoinnovad:/var/lib/Bitcoinnovad/
    networks:
      testnet:
        ipv4_address: 172.16.76.11
  
#  node2:
#    image: funkypenguin/bitcoinnova
#    container_name: bitcoinnovatest-node2
#    networks:
#      testnet:
#        ipv4_address: 172.16.76.12
  
#  node3:
#    image: funkypenguin/bitcoinnova
#    container_name: bitcoinnovatest-node3
#    networks:
#      testnet:
#        ipv4_address: 172.16.76.13

networks:
  testnet:
    ipam:
      config:
        - subnet: 172.16.76.0/24

